server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///dandp?serverTimezone=GMT&useSSL=false&charactEncoding=GMT+8
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: top.annoo.entity
logging:
  level:
    top.annoo.mapper: debug
    root: info